development:
  adapter: postgresql
  encoding: utf8
  database: dbc-hackathon_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: dbc-hackathon_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: dbc-hackathon_production
  pool: 5
  username:
  password: